Vishrut/build
persistenceOne/persistenceJS pull request #32
Opened 2022-08-09 13:17 UTC by vishrutsingh

### Additions
- added a GitHub pre-commit hook for formatting
- added npm package files for publishing
- added type declarations for the project
- added release hooks and jobs

### Changes
- package.json dependencies: Build is relatively small now

### Missing
- README.md: can be pushed in the next PR

2022-08-09 13:19 UTC, vishrutsingh commented
types directory is generated but required for build.

2022-08-10 05:56 UTC, Anmol1696 requested changes

2022-08-10 05:56 UTC, Anmol1696 commented on .github/workflows/RELEASE.yaml
> +          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
new line

2022-08-10 05:56 UTC, Anmol1696 commented on .npmrc
> +scripts-prepend-node-path=true
new line

2022-08-10 05:56 UTC, Anmol1696 commented on package.json
> +    "name": "persistenceonejs",
why the name change?

2022-08-10 06:05 UTC, Anmol1696 approved these changes
Just nits, LGTM

2022-08-10 14:02 UTC, vishrutsingh commented
have changed the scope of pre commit format to the whole repo for linting issues in directories other than src.

2022-08-10 14:02 UTC, Anmol1696 approved these changes
LGTM good work on running the linters

2022-08-10 14:06 UTC, merged